export const ENCODE_MESSAGE_REQUEST = 'ENCODE_MESSAGE_REQUEST';
export const ENCODE_MESSAGE_SUCCESS = 'ENCODE_MESSAGE_SUCCESS';
export const ENCODE_MESSAGE_FAILURE = 'ENCODE_MESSAGE_FAILURE';

export const DECODE_MESSAGE_REQUEST = 'DECODE_MESSAGE_REQUEST';
export const DECODE_MESSAGE_SUCCESS = 'DECODE_MESSAGE_SUCCESS';
export const DECODE_MESSAGE_FAILURE = 'DECODE_MESSAGE_FAILURE';